name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: riteshubale-01
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#58A6FF&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353

      - name: Push Snake Animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
